### ISSUE TITLE
How to declare a custom type in a ffi-function?

### ISSUE THREAD

**Issue by jkitchin** [tromey/emacs-ffi#16]
This might be related to Issue #15. I am trying to define this function (http://mongoc.org/libmongoc/current/mongoc_collection_insert.html) using emacs-ffi. It has this signature:

```
bool
mongoc_collection_insert (mongoc_collection_t *collection,
                          mongoc_insert_flags_t flags,
                          const bson_t *document,
                          const mongoc_write_concern_t *write_concern,
                          bson_error_t *error);
```

It looks like this is what it should be:

```
(define-ffi-function mongoc_collection_insert "mongoc_collection_insert"
  :bool
  (:pointer ??? :pointer :pointer :pointer))
```

but I can't figure out what to do for the mongoc_insert_flags_t type. Any tips? Thanks!

**Comment by tromey** [comment]
What you have to do is find the "ABI type" and use that.  There are a few ways you can do that.

One way is to read header files and track down the definition of the type.  You can possibly automate this using a compiler plugin or the like.

Another way is to use gdb and `ptype` the type to see what it resolves to.  For this you need debug symbols for the library.

**Comment by jkitchin** [comment]
Thanks for the tip. Is an "ABI type" one of the more fundamental types that your module has already defined as a :keyword? I looked here: http://mongoc.org/libmongoc/current/mongoc_insert_flags_t.html, and it looks like that type is basically going to be an int. Does that mean I would use :int? Or does it mean there is some way to create new :keyword-types. I am mostly curious now, it looks like I will probably stick with writing dynamic modules for anything complex with lots of custom types like this.

**Comment by tromey** [comment]
> Is an "ABI type" one of the more fundamental types that your module has already defined as a :keyword?

I guess it's not really a well-defined term, but basically it's the types that libffi knows about.  The main difficulties in this area are (1) unravelling typedefs in a way that works everywhere (it's normal in C for typedefs to be platform-specific) and (2) picking the correct underlying type for an enum (this is ABI-defined but libffi doesn't offer any help).

**Comment by jkitchin** [comment]
ok. Thanks for the clarification. It doesn't look like this issue needs to stay open, so I will close it.
